// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: client/rpc_regex.proto

package clientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncRegexDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastSynced    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_synced,json=lastSynced,proto3" json:"last_synced,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRegexDataRequest) Reset() {
	*x = SyncRegexDataRequest{}
	mi := &file_client_rpc_regex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRegexDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRegexDataRequest) ProtoMessage() {}

func (x *SyncRegexDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_rpc_regex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRegexDataRequest.ProtoReflect.Descriptor instead.
func (*SyncRegexDataRequest) Descriptor() ([]byte, []int) {
	return file_client_rpc_regex_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRegexDataRequest) GetLastSynced() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSynced
	}
	return nil
}

type SyncRegexDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsChanged     bool                   `protobuf:"varint,1,opt,name=is_changed,json=isChanged,proto3" json:"is_changed,omitempty"`
	Items         []*RegexData           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRegexDataResponse) Reset() {
	*x = SyncRegexDataResponse{}
	mi := &file_client_rpc_regex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRegexDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRegexDataResponse) ProtoMessage() {}

func (x *SyncRegexDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_rpc_regex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRegexDataResponse.ProtoReflect.Descriptor instead.
func (*SyncRegexDataResponse) Descriptor() ([]byte, []int) {
	return file_client_rpc_regex_proto_rawDescGZIP(), []int{1}
}

func (x *SyncRegexDataResponse) GetIsChanged() bool {
	if x != nil {
		return x.IsChanged
	}
	return false
}

func (x *SyncRegexDataResponse) GetItems() []*RegexData {
	if x != nil {
		return x.Items
	}
	return nil
}

type RegexData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Desc          string                 `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	RegexStr      string                 `protobuf:"bytes,2,opt,name=regex_str,json=regexStr,proto3" json:"regex_str,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegexData) Reset() {
	*x = RegexData{}
	mi := &file_client_rpc_regex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegexData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegexData) ProtoMessage() {}

func (x *RegexData) ProtoReflect() protoreflect.Message {
	mi := &file_client_rpc_regex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegexData.ProtoReflect.Descriptor instead.
func (*RegexData) Descriptor() ([]byte, []int) {
	return file_client_rpc_regex_proto_rawDescGZIP(), []int{2}
}

func (x *RegexData) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *RegexData) GetRegexStr() string {
	if x != nil {
		return x.RegexStr
	}
	return ""
}

func (x *RegexData) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RegexData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateRegexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	RegexStr      string                 `protobuf:"bytes,2,opt,name=regex_str,json=regexStr,proto3" json:"regex_str,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRegexRequest) Reset() {
	*x = CreateRegexRequest{}
	mi := &file_client_rpc_regex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRegexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegexRequest) ProtoMessage() {}

func (x *CreateRegexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_rpc_regex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegexRequest.ProtoReflect.Descriptor instead.
func (*CreateRegexRequest) Descriptor() ([]byte, []int) {
	return file_client_rpc_regex_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRegexRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateRegexRequest) GetRegexStr() string {
	if x != nil {
		return x.RegexStr
	}
	return ""
}

func (x *CreateRegexRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateRegexRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateRegexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRegexResponse) Reset() {
	*x = CreateRegexResponse{}
	mi := &file_client_rpc_regex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRegexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRegexResponse) ProtoMessage() {}

func (x *CreateRegexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_rpc_regex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRegexResponse.ProtoReflect.Descriptor instead.
func (*CreateRegexResponse) Descriptor() ([]byte, []int) {
	return file_client_rpc_regex_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRegexResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateRegexResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_client_rpc_regex_proto protoreflect.FileDescriptor

const file_client_rpc_regex_proto_rawDesc = "" +
	"\n" +
	"\x16client/rpc_regex.proto\x12\x06client\x1a\x1fgoogle/protobuf/timestamp.proto\"S\n" +
	"\x14SyncRegexDataRequest\x12;\n" +
	"\vlast_synced\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSynced\"_\n" +
	"\x15SyncRegexDataResponse\x12\x1d\n" +
	"\n" +
	"is_changed\x18\x01 \x01(\bR\tisChanged\x12'\n" +
	"\x05items\x18\x02 \x03(\v2\x11.client.RegexDataR\x05items\"j\n" +
	"\tRegexData\x12\x12\n" +
	"\x04desc\x18\x01 \x01(\tR\x04desc\x12\x1b\n" +
	"\tregex_str\x18\x02 \x01(\tR\bregexStr\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"m\n" +
	"\x12CreateRegexRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tregex_str\x18\x02 \x01(\tR\bregexStr\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"j\n" +
	"\x13CreateRegexResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xa0\x01\n" +
	"\fRegexService\x12F\n" +
	"\vCreateRegex\x12\x1a.client.CreateRegexRequest\x1a\x1b.client.CreateRegexResponse\x12H\n" +
	"\tSyncRegex\x12\x1c.client.SyncRegexDataRequest\x1a\x1d.client.SyncRegexDataResponseB\x19Z\x17axilock-runner/clientpbb\x06proto3"

var (
	file_client_rpc_regex_proto_rawDescOnce sync.Once
	file_client_rpc_regex_proto_rawDescData []byte
)

func file_client_rpc_regex_proto_rawDescGZIP() []byte {
	file_client_rpc_regex_proto_rawDescOnce.Do(func() {
		file_client_rpc_regex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_rpc_regex_proto_rawDesc), len(file_client_rpc_regex_proto_rawDesc)))
	})
	return file_client_rpc_regex_proto_rawDescData
}

var file_client_rpc_regex_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_client_rpc_regex_proto_goTypes = []any{
	(*SyncRegexDataRequest)(nil),  // 0: client.SyncRegexDataRequest
	(*SyncRegexDataResponse)(nil), // 1: client.SyncRegexDataResponse
	(*RegexData)(nil),             // 2: client.RegexData
	(*CreateRegexRequest)(nil),    // 3: client.CreateRegexRequest
	(*CreateRegexResponse)(nil),   // 4: client.CreateRegexResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_client_rpc_regex_proto_depIdxs = []int32{
	5, // 0: client.SyncRegexDataRequest.last_synced:type_name -> google.protobuf.Timestamp
	2, // 1: client.SyncRegexDataResponse.items:type_name -> client.RegexData
	5, // 2: client.CreateRegexResponse.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: client.RegexService.CreateRegex:input_type -> client.CreateRegexRequest
	0, // 4: client.RegexService.SyncRegex:input_type -> client.SyncRegexDataRequest
	4, // 5: client.RegexService.CreateRegex:output_type -> client.CreateRegexResponse
	1, // 6: client.RegexService.SyncRegex:output_type -> client.SyncRegexDataResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_client_rpc_regex_proto_init() }
func file_client_rpc_regex_proto_init() {
	if File_client_rpc_regex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_rpc_regex_proto_rawDesc), len(file_client_rpc_regex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_rpc_regex_proto_goTypes,
		DependencyIndexes: file_client_rpc_regex_proto_depIdxs,
		MessageInfos:      file_client_rpc_regex_proto_msgTypes,
	}.Build()
	File_client_rpc_regex_proto = out.File
	file_client_rpc_regex_proto_goTypes = nil
	file_client_rpc_regex_proto_depIdxs = nil
}
