// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: client/rpc_alerts.proto

package clientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	LineNumber    int64                  `protobuf:"varint,3,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"`
	CommitId      string                 `protobuf:"bytes,4,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	SecretType    string                 `protobuf:"bytes,5,opt,name=secret_type,json=secretType,proto3" json:"secret_type,omitempty"`
	IsVerified    bool                   `protobuf:"varint,6,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	Fragment      string                 `protobuf:"bytes,7,opt,name=fragment,proto3" json:"fragment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretAlertRequest) Reset() {
	*x = SecretAlertRequest{}
	mi := &file_client_rpc_alerts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretAlertRequest) ProtoMessage() {}

func (x *SecretAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_rpc_alerts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretAlertRequest.ProtoReflect.Descriptor instead.
func (*SecretAlertRequest) Descriptor() ([]byte, []int) {
	return file_client_rpc_alerts_proto_rawDescGZIP(), []int{0}
}

func (x *SecretAlertRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SecretAlertRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *SecretAlertRequest) GetLineNumber() int64 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *SecretAlertRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *SecretAlertRequest) GetSecretType() string {
	if x != nil {
		return x.SecretType
	}
	return ""
}

func (x *SecretAlertRequest) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *SecretAlertRequest) GetFragment() string {
	if x != nil {
		return x.Fragment
	}
	return ""
}

type SecretAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretAlertResponse) Reset() {
	*x = SecretAlertResponse{}
	mi := &file_client_rpc_alerts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretAlertResponse) ProtoMessage() {}

func (x *SecretAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_rpc_alerts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretAlertResponse.ProtoReflect.Descriptor instead.
func (*SecretAlertResponse) Descriptor() ([]byte, []int) {
	return file_client_rpc_alerts_proto_rawDescGZIP(), []int{1}
}

func (x *SecretAlertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_client_rpc_alerts_proto protoreflect.FileDescriptor

const file_client_rpc_alerts_proto_rawDesc = "" +
	"\n" +
	"\x17client/rpc_alerts.proto\x12\x06client\"\xe1\x01\n" +
	"\x12SecretAlertRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x1f\n" +
	"\vline_number\x18\x03 \x01(\x03R\n" +
	"lineNumber\x12\x1b\n" +
	"\tcommit_id\x18\x04 \x01(\tR\bcommitId\x12\x1f\n" +
	"\vsecret_type\x18\x05 \x01(\tR\n" +
	"secretType\x12\x1f\n" +
	"\vis_verified\x18\x06 \x01(\bR\n" +
	"isVerified\x12\x1a\n" +
	"\bfragment\x18\a \x01(\tR\bfragment\"/\n" +
	"\x13SecretAlertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2X\n" +
	"\fAlertService\x12H\n" +
	"\vSecretAlert\x12\x1a.client.SecretAlertRequest\x1a\x1b.client.SecretAlertResponse\"\x00B\x19Z\x17axilock-runner/clientpbb\x06proto3"

var (
	file_client_rpc_alerts_proto_rawDescOnce sync.Once
	file_client_rpc_alerts_proto_rawDescData []byte
)

func file_client_rpc_alerts_proto_rawDescGZIP() []byte {
	file_client_rpc_alerts_proto_rawDescOnce.Do(func() {
		file_client_rpc_alerts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_rpc_alerts_proto_rawDesc), len(file_client_rpc_alerts_proto_rawDesc)))
	})
	return file_client_rpc_alerts_proto_rawDescData
}

var file_client_rpc_alerts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_rpc_alerts_proto_goTypes = []any{
	(*SecretAlertRequest)(nil),  // 0: client.SecretAlertRequest
	(*SecretAlertResponse)(nil), // 1: client.SecretAlertResponse
}
var file_client_rpc_alerts_proto_depIdxs = []int32{
	0, // 0: client.AlertService.SecretAlert:input_type -> client.SecretAlertRequest
	1, // 1: client.AlertService.SecretAlert:output_type -> client.SecretAlertResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_rpc_alerts_proto_init() }
func file_client_rpc_alerts_proto_init() {
	if File_client_rpc_alerts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_rpc_alerts_proto_rawDesc), len(file_client_rpc_alerts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_rpc_alerts_proto_goTypes,
		DependencyIndexes: file_client_rpc_alerts_proto_depIdxs,
		MessageInfos:      file_client_rpc_alerts_proto_msgTypes,
	}.Build()
	File_client_rpc_alerts_proto = out.File
	file_client_rpc_alerts_proto_goTypes = nil
	file_client_rpc_alerts_proto_depIdxs = nil
}
