// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: client/rpc_session.proto

package clientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAuthSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitToken     string                 `protobuf:"bytes,1,opt,name=init_token,json=initToken,proto3" json:"init_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthSessionRequest) Reset() {
	*x = CreateAuthSessionRequest{}
	mi := &file_client_rpc_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthSessionRequest) ProtoMessage() {}

func (x *CreateAuthSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_rpc_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateAuthSessionRequest) Descriptor() ([]byte, []int) {
	return file_client_rpc_session_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAuthSessionRequest) GetInitToken() string {
	if x != nil {
		return x.InitToken
	}
	return ""
}

type CreateAuthSessionResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CliAuthToken       string                 `protobuf:"bytes,1,opt,name=cli_auth_token,json=cliAuthToken,proto3" json:"cli_auth_token,omitempty"`
	CliauthTokenExpiry *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=cliauth_token_expiry,json=cliauthTokenExpiry,proto3" json:"cliauth_token_expiry,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateAuthSessionResponse) Reset() {
	*x = CreateAuthSessionResponse{}
	mi := &file_client_rpc_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthSessionResponse) ProtoMessage() {}

func (x *CreateAuthSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_rpc_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateAuthSessionResponse) Descriptor() ([]byte, []int) {
	return file_client_rpc_session_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAuthSessionResponse) GetCliAuthToken() string {
	if x != nil {
		return x.CliAuthToken
	}
	return ""
}

func (x *CreateAuthSessionResponse) GetCliauthTokenExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.CliauthTokenExpiry
	}
	return nil
}

var File_client_rpc_session_proto protoreflect.FileDescriptor

const file_client_rpc_session_proto_rawDesc = "" +
	"\n" +
	"\x18client/rpc_session.proto\x12\x06client\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\x18CreateAuthSessionRequest\x12\x1d\n" +
	"\n" +
	"init_token\x18\x01 \x01(\tR\tinitToken\"\x8f\x01\n" +
	"\x19CreateAuthSessionResponse\x12$\n" +
	"\x0ecli_auth_token\x18\x01 \x01(\tR\fcliAuthToken\x12L\n" +
	"\x14cliauth_token_expiry\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x12cliauthTokenExpiry2j\n" +
	"\x0eSessionService\x12X\n" +
	"\x11CreateAuthSession\x12 .client.CreateAuthSessionRequest\x1a!.client.CreateAuthSessionResponseB\x19Z\x17axilock-runner/clientpbb\x06proto3"

var (
	file_client_rpc_session_proto_rawDescOnce sync.Once
	file_client_rpc_session_proto_rawDescData []byte
)

func file_client_rpc_session_proto_rawDescGZIP() []byte {
	file_client_rpc_session_proto_rawDescOnce.Do(func() {
		file_client_rpc_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_rpc_session_proto_rawDesc), len(file_client_rpc_session_proto_rawDesc)))
	})
	return file_client_rpc_session_proto_rawDescData
}

var file_client_rpc_session_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_rpc_session_proto_goTypes = []any{
	(*CreateAuthSessionRequest)(nil),  // 0: client.CreateAuthSessionRequest
	(*CreateAuthSessionResponse)(nil), // 1: client.CreateAuthSessionResponse
	(*timestamppb.Timestamp)(nil),     // 2: google.protobuf.Timestamp
}
var file_client_rpc_session_proto_depIdxs = []int32{
	2, // 0: client.CreateAuthSessionResponse.cliauth_token_expiry:type_name -> google.protobuf.Timestamp
	0, // 1: client.SessionService.CreateAuthSession:input_type -> client.CreateAuthSessionRequest
	1, // 2: client.SessionService.CreateAuthSession:output_type -> client.CreateAuthSessionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_client_rpc_session_proto_init() }
func file_client_rpc_session_proto_init() {
	if File_client_rpc_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_rpc_session_proto_rawDesc), len(file_client_rpc_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_rpc_session_proto_goTypes,
		DependencyIndexes: file_client_rpc_session_proto_depIdxs,
		MessageInfos:      file_client_rpc_session_proto_msgTypes,
	}.Build()
	File_client_rpc_session_proto = out.File
	file_client_rpc_session_proto_goTypes = nil
	file_client_rpc_session_proto_depIdxs = nil
}
