// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: client/rpc_healthcheck.proto

package clientpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ARCH int32

const (
	ARCH_ARCH_UNSPECIFIED ARCH = 0
	ARCH_ARCH_ARM64       ARCH = 1
	ARCH_ARCH_AMD64       ARCH = 2
)

// Enum value maps for ARCH.
var (
	ARCH_name = map[int32]string{
		0: "ARCH_UNSPECIFIED",
		1: "ARCH_ARM64",
		2: "ARCH_AMD64",
	}
	ARCH_value = map[string]int32{
		"ARCH_UNSPECIFIED": 0,
		"ARCH_ARM64":       1,
		"ARCH_AMD64":       2,
	}
)

func (x ARCH) Enum() *ARCH {
	p := new(ARCH)
	*p = x
	return p
}

func (x ARCH) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ARCH) Descriptor() protoreflect.EnumDescriptor {
	return file_client_rpc_healthcheck_proto_enumTypes[0].Descriptor()
}

func (ARCH) Type() protoreflect.EnumType {
	return &file_client_rpc_healthcheck_proto_enumTypes[0]
}

func (x ARCH) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ARCH.Descriptor instead.
func (ARCH) EnumDescriptor() ([]byte, []int) {
	return file_client_rpc_healthcheck_proto_rawDescGZIP(), []int{0}
}

type OS int32

const (
	OS_OS_UNSPECIFIED OS = 0
	OS_OS_WINDOWS     OS = 1
	OS_OS_LINUX       OS = 2
	OS_OS_DARWIN      OS = 3
)

// Enum value maps for OS.
var (
	OS_name = map[int32]string{
		0: "OS_UNSPECIFIED",
		1: "OS_WINDOWS",
		2: "OS_LINUX",
		3: "OS_DARWIN",
	}
	OS_value = map[string]int32{
		"OS_UNSPECIFIED": 0,
		"OS_WINDOWS":     1,
		"OS_LINUX":       2,
		"OS_DARWIN":      3,
	}
)

func (x OS) Enum() *OS {
	p := new(OS)
	*p = x
	return p
}

func (x OS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OS) Descriptor() protoreflect.EnumDescriptor {
	return file_client_rpc_healthcheck_proto_enumTypes[1].Descriptor()
}

func (OS) Type() protoreflect.EnumType {
	return &file_client_rpc_healthcheck_proto_enumTypes[1]
}

func (x OS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OS.Descriptor instead.
func (OS) EnumDescriptor() ([]byte, []int) {
	return file_client_rpc_healthcheck_proto_rawDescGZIP(), []int{1}
}

type Env int32

const (
	Env_ENV_UNSPECIFIED Env = 0
	Env_ENV_DEV         Env = 1
	Env_ENV_RELEASE     Env = 2
)

// Enum value maps for Env.
var (
	Env_name = map[int32]string{
		0: "ENV_UNSPECIFIED",
		1: "ENV_DEV",
		2: "ENV_RELEASE",
	}
	Env_value = map[string]int32{
		"ENV_UNSPECIFIED": 0,
		"ENV_DEV":         1,
		"ENV_RELEASE":     2,
	}
)

func (x Env) Enum() *Env {
	p := new(Env)
	*p = x
	return p
}

func (x Env) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Env) Descriptor() protoreflect.EnumDescriptor {
	return file_client_rpc_healthcheck_proto_enumTypes[2].Descriptor()
}

func (Env) Type() protoreflect.EnumType {
	return &file_client_rpc_healthcheck_proto_enumTypes[2]
}

func (x Env) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Env.Descriptor instead.
func (Env) EnumDescriptor() ([]byte, []int) {
	return file_client_rpc_healthcheck_proto_rawDescGZIP(), []int{2}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVer     string                 `protobuf:"bytes,1,opt,name=client_ver,json=clientVer,proto3" json:"client_ver,omitempty"`
	Org           string                 `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	AuthToken     string                 `protobuf:"bytes,3,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	RepoUrl       string                 `protobuf:"bytes,4,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_client_rpc_healthcheck_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_rpc_healthcheck_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_client_rpc_healthcheck_proto_rawDescGZIP(), []int{0}
}

func (x *HealthRequest) GetClientVer() string {
	if x != nil {
		return x.ClientVer
	}
	return ""
}

func (x *HealthRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *HealthRequest) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

func (x *HealthRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BackendVer      string                 `protobuf:"bytes,1,opt,name=backend_ver,json=backendVer,proto3" json:"backend_ver,omitempty"`
	LatestClientver string                 `protobuf:"bytes,2,opt,name=latest_clientver,json=latestClientver,proto3" json:"latest_clientver,omitempty"`
	Toupdate        bool                   `protobuf:"varint,3,opt,name=toupdate,proto3" json:"toupdate,omitempty"`
	Hookslist       string                 `protobuf:"bytes,4,opt,name=hookslist,proto3" json:"hookslist,omitempty"` //TODO : handle case when hooks are updated
	Cliupdatepath   string                 `protobuf:"bytes,5,opt,name=cliupdatepath,proto3" json:"cliupdatepath,omitempty"`
	Systemstatus    string                 `protobuf:"bytes,6,opt,name=systemstatus,proto3" json:"systemstatus,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_client_rpc_healthcheck_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_rpc_healthcheck_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_client_rpc_healthcheck_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetBackendVer() string {
	if x != nil {
		return x.BackendVer
	}
	return ""
}

func (x *HealthResponse) GetLatestClientver() string {
	if x != nil {
		return x.LatestClientver
	}
	return ""
}

func (x *HealthResponse) GetToupdate() bool {
	if x != nil {
		return x.Toupdate
	}
	return false
}

func (x *HealthResponse) GetHookslist() string {
	if x != nil {
		return x.Hookslist
	}
	return ""
}

func (x *HealthResponse) GetCliupdatepath() string {
	if x != nil {
		return x.Cliupdatepath
	}
	return ""
}

func (x *HealthResponse) GetSystemstatus() string {
	if x != nil {
		return x.Systemstatus
	}
	return ""
}

func (x *HealthResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ClientUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVer     string                 `protobuf:"bytes,1,opt,name=client_ver,json=clientVer,proto3" json:"client_ver,omitempty"`
	Os            OS                     `protobuf:"varint,2,opt,name=os,proto3,enum=client.OS" json:"os,omitempty"`
	Arch          ARCH                   `protobuf:"varint,3,opt,name=arch,proto3,enum=client.ARCH" json:"arch,omitempty"`
	Environment   Env                    `protobuf:"varint,4,opt,name=environment,proto3,enum=client.Env" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientUpdateRequest) Reset() {
	*x = ClientUpdateRequest{}
	mi := &file_client_rpc_healthcheck_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientUpdateRequest) ProtoMessage() {}

func (x *ClientUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_rpc_healthcheck_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientUpdateRequest.ProtoReflect.Descriptor instead.
func (*ClientUpdateRequest) Descriptor() ([]byte, []int) {
	return file_client_rpc_healthcheck_proto_rawDescGZIP(), []int{2}
}

func (x *ClientUpdateRequest) GetClientVer() string {
	if x != nil {
		return x.ClientVer
	}
	return ""
}

func (x *ClientUpdateRequest) GetOs() OS {
	if x != nil {
		return x.Os
	}
	return OS_OS_UNSPECIFIED
}

func (x *ClientUpdateRequest) GetArch() ARCH {
	if x != nil {
		return x.Arch
	}
	return ARCH_ARCH_UNSPECIFIED
}

func (x *ClientUpdateRequest) GetEnvironment() Env {
	if x != nil {
		return x.Environment
	}
	return Env_ENV_UNSPECIFIED
}

type ClientUpdateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ToUpdate         bool                   `protobuf:"varint,1,opt,name=to_update,json=toUpdate,proto3" json:"to_update,omitempty"`
	LatestClientver  string                 `protobuf:"bytes,2,opt,name=latest_clientver,json=latestClientver,proto3" json:"latest_clientver,omitempty"`
	ClientUpdatePath string                 `protobuf:"bytes,3,opt,name=client_update_path,json=clientUpdatePath,proto3" json:"client_update_path,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClientUpdateResponse) Reset() {
	*x = ClientUpdateResponse{}
	mi := &file_client_rpc_healthcheck_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientUpdateResponse) ProtoMessage() {}

func (x *ClientUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_rpc_healthcheck_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientUpdateResponse.ProtoReflect.Descriptor instead.
func (*ClientUpdateResponse) Descriptor() ([]byte, []int) {
	return file_client_rpc_healthcheck_proto_rawDescGZIP(), []int{3}
}

func (x *ClientUpdateResponse) GetToUpdate() bool {
	if x != nil {
		return x.ToUpdate
	}
	return false
}

func (x *ClientUpdateResponse) GetLatestClientver() string {
	if x != nil {
		return x.LatestClientver
	}
	return ""
}

func (x *ClientUpdateResponse) GetClientUpdatePath() string {
	if x != nil {
		return x.ClientUpdatePath
	}
	return ""
}

var File_client_rpc_healthcheck_proto protoreflect.FileDescriptor

const file_client_rpc_healthcheck_proto_rawDesc = "" +
	"\n" +
	"\x1cclient/rpc_healthcheck.proto\x12\x06client\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n" +
	"\rHealthRequest\x12\x1d\n" +
	"\n" +
	"client_ver\x18\x01 \x01(\tR\tclientVer\x12\x10\n" +
	"\x03org\x18\x02 \x01(\tR\x03org\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x03 \x01(\tR\tauthToken\x12\x19\n" +
	"\brepo_url\x18\x04 \x01(\tR\arepoUrl\"\x9b\x02\n" +
	"\x0eHealthResponse\x12\x1f\n" +
	"\vbackend_ver\x18\x01 \x01(\tR\n" +
	"backendVer\x12)\n" +
	"\x10latest_clientver\x18\x02 \x01(\tR\x0flatestClientver\x12\x1a\n" +
	"\btoupdate\x18\x03 \x01(\bR\btoupdate\x12\x1c\n" +
	"\thookslist\x18\x04 \x01(\tR\thookslist\x12$\n" +
	"\rcliupdatepath\x18\x05 \x01(\tR\rcliupdatepath\x12\"\n" +
	"\fsystemstatus\x18\x06 \x01(\tR\fsystemstatus\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa1\x01\n" +
	"\x13ClientUpdateRequest\x12\x1d\n" +
	"\n" +
	"client_ver\x18\x01 \x01(\tR\tclientVer\x12\x1a\n" +
	"\x02os\x18\x02 \x01(\x0e2\n" +
	".client.OSR\x02os\x12 \n" +
	"\x04arch\x18\x03 \x01(\x0e2\f.client.ARCHR\x04arch\x12-\n" +
	"\venvironment\x18\x04 \x01(\x0e2\v.client.EnvR\venvironment\"\x8c\x01\n" +
	"\x14ClientUpdateResponse\x12\x1b\n" +
	"\tto_update\x18\x01 \x01(\bR\btoUpdate\x12)\n" +
	"\x10latest_clientver\x18\x02 \x01(\tR\x0flatestClientver\x12,\n" +
	"\x12client_update_path\x18\x03 \x01(\tR\x10clientUpdatePath*<\n" +
	"\x04ARCH\x12\x14\n" +
	"\x10ARCH_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ARCH_ARM64\x10\x01\x12\x0e\n" +
	"\n" +
	"ARCH_AMD64\x10\x02*E\n" +
	"\x02OS\x12\x12\n" +
	"\x0eOS_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"OS_WINDOWS\x10\x01\x12\f\n" +
	"\bOS_LINUX\x10\x02\x12\r\n" +
	"\tOS_DARWIN\x10\x03*8\n" +
	"\x03Env\x12\x13\n" +
	"\x0fENV_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aENV_DEV\x10\x01\x12\x0f\n" +
	"\vENV_RELEASE\x10\x022\x9d\x01\n" +
	"\rHealthService\x12L\n" +
	"\x0fClientUpdateRpc\x12\x1b.client.ClientUpdateRequest\x1a\x1c.client.ClientUpdateResponse\x12>\n" +
	"\rDoHealthCheck\x12\x15.client.HealthRequest\x1a\x16.client.HealthResponseB\x19Z\x17axilock-runner/clientpbb\x06proto3"

var (
	file_client_rpc_healthcheck_proto_rawDescOnce sync.Once
	file_client_rpc_healthcheck_proto_rawDescData []byte
)

func file_client_rpc_healthcheck_proto_rawDescGZIP() []byte {
	file_client_rpc_healthcheck_proto_rawDescOnce.Do(func() {
		file_client_rpc_healthcheck_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_rpc_healthcheck_proto_rawDesc), len(file_client_rpc_healthcheck_proto_rawDesc)))
	})
	return file_client_rpc_healthcheck_proto_rawDescData
}

var file_client_rpc_healthcheck_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_client_rpc_healthcheck_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_client_rpc_healthcheck_proto_goTypes = []any{
	(ARCH)(0),                     // 0: client.ARCH
	(OS)(0),                       // 1: client.OS
	(Env)(0),                      // 2: client.Env
	(*HealthRequest)(nil),         // 3: client.HealthRequest
	(*HealthResponse)(nil),        // 4: client.HealthResponse
	(*ClientUpdateRequest)(nil),   // 5: client.ClientUpdateRequest
	(*ClientUpdateResponse)(nil),  // 6: client.ClientUpdateResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_client_rpc_healthcheck_proto_depIdxs = []int32{
	7, // 0: client.HealthResponse.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: client.ClientUpdateRequest.os:type_name -> client.OS
	0, // 2: client.ClientUpdateRequest.arch:type_name -> client.ARCH
	2, // 3: client.ClientUpdateRequest.environment:type_name -> client.Env
	5, // 4: client.HealthService.ClientUpdateRpc:input_type -> client.ClientUpdateRequest
	3, // 5: client.HealthService.DoHealthCheck:input_type -> client.HealthRequest
	6, // 6: client.HealthService.ClientUpdateRpc:output_type -> client.ClientUpdateResponse
	4, // 7: client.HealthService.DoHealthCheck:output_type -> client.HealthResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_client_rpc_healthcheck_proto_init() }
func file_client_rpc_healthcheck_proto_init() {
	if File_client_rpc_healthcheck_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_rpc_healthcheck_proto_rawDesc), len(file_client_rpc_healthcheck_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_rpc_healthcheck_proto_goTypes,
		DependencyIndexes: file_client_rpc_healthcheck_proto_depIdxs,
		EnumInfos:         file_client_rpc_healthcheck_proto_enumTypes,
		MessageInfos:      file_client_rpc_healthcheck_proto_msgTypes,
	}.Build()
	File_client_rpc_healthcheck_proto = out.File
	file_client_rpc_healthcheck_proto_goTypes = nil
	file_client_rpc_healthcheck_proto_depIdxs = nil
}
