// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.3
// source: rpc_inteegrations.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIntegrationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrontendVer   string                 `protobuf:"bytes,1,opt,name=frontend_ver,json=frontendVer,proto3" json:"frontend_ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntegrationsRequest) Reset() {
	*x = GetIntegrationsRequest{}
	mi := &file_rpc_inteegrations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntegrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationsRequest) ProtoMessage() {}

func (x *GetIntegrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_inteegrations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationsRequest.ProtoReflect.Descriptor instead.
func (*GetIntegrationsRequest) Descriptor() ([]byte, []int) {
	return file_rpc_inteegrations_proto_rawDescGZIP(), []int{0}
}

func (x *GetIntegrationsRequest) GetFrontendVer() string {
	if x != nil {
		return x.FrontendVer
	}
	return ""
}

type IntegrationType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ActionUrl     string                 `protobuf:"bytes,3,opt,name=action_url,json=actionUrl,proto3" json:"action_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationType) Reset() {
	*x = IntegrationType{}
	mi := &file_rpc_inteegrations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationType) ProtoMessage() {}

func (x *IntegrationType) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_inteegrations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationType.ProtoReflect.Descriptor instead.
func (*IntegrationType) Descriptor() ([]byte, []int) {
	return file_rpc_inteegrations_proto_rawDescGZIP(), []int{1}
}

func (x *IntegrationType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IntegrationType) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *IntegrationType) GetActionUrl() string {
	if x != nil {
		return x.ActionUrl
	}
	return ""
}

type GetIntegrationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Integrations  []*IntegrationType     `protobuf:"bytes,1,rep,name=integrations,proto3" json:"integrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntegrationsResponse) Reset() {
	*x = GetIntegrationsResponse{}
	mi := &file_rpc_inteegrations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntegrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationsResponse) ProtoMessage() {}

func (x *GetIntegrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_inteegrations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationsResponse.ProtoReflect.Descriptor instead.
func (*GetIntegrationsResponse) Descriptor() ([]byte, []int) {
	return file_rpc_inteegrations_proto_rawDescGZIP(), []int{2}
}

func (x *GetIntegrationsResponse) GetIntegrations() []*IntegrationType {
	if x != nil {
		return x.Integrations
	}
	return nil
}

var File_rpc_inteegrations_proto protoreflect.FileDescriptor

var file_rpc_inteegrations_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x70, 0x63, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b,
	0x0a, 0x16, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x64, 0x5f, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x56, 0x65, 0x72, 0x22, 0x5c, 0x0a, 0x0f, 0x49,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x22, 0x52, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x2e,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0c, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0x61, 0x0a,
	0x13, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x14, 0x5a, 0x12, 0x73, 0x65, 0x63, 0x6b, 0x72, 0x69, 0x74, 0x2d, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_inteegrations_proto_rawDescOnce sync.Once
	file_rpc_inteegrations_proto_rawDescData = file_rpc_inteegrations_proto_rawDesc
)

func file_rpc_inteegrations_proto_rawDescGZIP() []byte {
	file_rpc_inteegrations_proto_rawDescOnce.Do(func() {
		file_rpc_inteegrations_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_inteegrations_proto_rawDescData)
	})
	return file_rpc_inteegrations_proto_rawDescData
}

var file_rpc_inteegrations_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_inteegrations_proto_goTypes = []any{
	(*GetIntegrationsRequest)(nil),  // 0: pb.GetIntegrationsRequest
	(*IntegrationType)(nil),         // 1: pb.IntegrationType
	(*GetIntegrationsResponse)(nil), // 2: pb.GetIntegrationsResponse
}
var file_rpc_inteegrations_proto_depIdxs = []int32{
	1, // 0: pb.GetIntegrationsResponse.integrations:type_name -> pb.IntegrationType
	0, // 1: pb.IntegrationsService.GetIntegrations:input_type -> pb.GetIntegrationsRequest
	2, // 2: pb.IntegrationsService.GetIntegrations:output_type -> pb.GetIntegrationsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_inteegrations_proto_init() }
func file_rpc_inteegrations_proto_init() {
	if File_rpc_inteegrations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_inteegrations_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_inteegrations_proto_goTypes,
		DependencyIndexes: file_rpc_inteegrations_proto_depIdxs,
		MessageInfos:      file_rpc_inteegrations_proto_msgTypes,
	}.Build()
	File_rpc_inteegrations_proto = out.File
	file_rpc_inteegrations_proto_rawDesc = nil
	file_rpc_inteegrations_proto_goTypes = nil
	file_rpc_inteegrations_proto_depIdxs = nil
}
