// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: rpc_session.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionService_CreateAuthSession_FullMethodName        = "/pb.SessionService/CreateAuthSession"
	SessionService_CreateCommitSessionToken_FullMethodName = "/pb.SessionService/CreateCommitSessionToken"
)

// SessionServiceClient is the client API for SessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionServiceClient interface {
	CreateAuthSession(ctx context.Context, in *CreateAuthSessionRequest, opts ...grpc.CallOption) (*CreateAuthSessionResponse, error)
	CreateCommitSessionToken(ctx context.Context, in *CreateCommitSessionTokenRequest, opts ...grpc.CallOption) (*CreateCommitSessionTokenResponse, error)
}

type sessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionServiceClient(cc grpc.ClientConnInterface) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) CreateAuthSession(ctx context.Context, in *CreateAuthSessionRequest, opts ...grpc.CallOption) (*CreateAuthSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAuthSessionResponse)
	err := c.cc.Invoke(ctx, SessionService_CreateAuthSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) CreateCommitSessionToken(ctx context.Context, in *CreateCommitSessionTokenRequest, opts ...grpc.CallOption) (*CreateCommitSessionTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCommitSessionTokenResponse)
	err := c.cc.Invoke(ctx, SessionService_CreateCommitSessionToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServiceServer is the server API for SessionService service.
// All implementations must embed UnimplementedSessionServiceServer
// for forward compatibility.
type SessionServiceServer interface {
	CreateAuthSession(context.Context, *CreateAuthSessionRequest) (*CreateAuthSessionResponse, error)
	CreateCommitSessionToken(context.Context, *CreateCommitSessionTokenRequest) (*CreateCommitSessionTokenResponse, error)
	mustEmbedUnimplementedSessionServiceServer()
}

// UnimplementedSessionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionServiceServer struct{}

func (UnimplementedSessionServiceServer) CreateAuthSession(context.Context, *CreateAuthSessionRequest) (*CreateAuthSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAuthSession not implemented")
}
func (UnimplementedSessionServiceServer) CreateCommitSessionToken(context.Context, *CreateCommitSessionTokenRequest) (*CreateCommitSessionTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCommitSessionToken not implemented")
}
func (UnimplementedSessionServiceServer) mustEmbedUnimplementedSessionServiceServer() {}
func (UnimplementedSessionServiceServer) testEmbeddedByValue()                        {}

// UnsafeSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionServiceServer will
// result in compilation errors.
type UnsafeSessionServiceServer interface {
	mustEmbedUnimplementedSessionServiceServer()
}

func RegisterSessionServiceServer(s grpc.ServiceRegistrar, srv SessionServiceServer) {
	// If the following call pancis, it indicates UnimplementedSessionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionService_ServiceDesc, srv)
}

func _SessionService_CreateAuthSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).CreateAuthSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_CreateAuthSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).CreateAuthSession(ctx, req.(*CreateAuthSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_CreateCommitSessionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommitSessionTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).CreateCommitSessionToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionService_CreateCommitSessionToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).CreateCommitSessionToken(ctx, req.(*CreateCommitSessionTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionService_ServiceDesc is the grpc.ServiceDesc for SessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAuthSession",
			Handler:    _SessionService_CreateAuthSession_Handler,
		},
		{
			MethodName: "CreateCommitSessionToken",
			Handler:    _SessionService_CreateCommitSessionToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc_session.proto",
}
