// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: rpc_metadata.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallerInitRequest_State int32

const (
	InstallerInitRequest_STATE_UNSPECIFIED InstallerInitRequest_State = 0
	InstallerInitRequest_STATE_INIT        InstallerInitRequest_State = 1
	InstallerInitRequest_STATE_DONE        InstallerInitRequest_State = 2
)

// Enum value maps for InstallerInitRequest_State.
var (
	InstallerInitRequest_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_INIT",
		2: "STATE_DONE",
	}
	InstallerInitRequest_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_INIT":        1,
		"STATE_DONE":        2,
	}
)

func (x InstallerInitRequest_State) Enum() *InstallerInitRequest_State {
	p := new(InstallerInitRequest_State)
	*p = x
	return p
}

func (x InstallerInitRequest_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstallerInitRequest_State) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_metadata_proto_enumTypes[0].Descriptor()
}

func (InstallerInitRequest_State) Type() protoreflect.EnumType {
	return &file_rpc_metadata_proto_enumTypes[0]
}

func (x InstallerInitRequest_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstallerInitRequest_State.Descriptor instead.
func (InstallerInitRequest_State) EnumDescriptor() ([]byte, []int) {
	return file_rpc_metadata_proto_rawDescGZIP(), []int{0, 0}
}

type InstallerInitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   InstallerInitRequest_State `protobuf:"varint,1,opt,name=status,proto3,enum=pb.InstallerInitRequest_State" json:"status,omitempty"`
	Metadata string                     `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *InstallerInitRequest) Reset() {
	*x = InstallerInitRequest{}
	mi := &file_rpc_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallerInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallerInitRequest) ProtoMessage() {}

func (x *InstallerInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallerInitRequest.ProtoReflect.Descriptor instead.
func (*InstallerInitRequest) Descriptor() ([]byte, []int) {
	return file_rpc_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *InstallerInitRequest) GetStatus() InstallerInitRequest_State {
	if x != nil {
		return x.Status
	}
	return InstallerInitRequest_STATE_UNSPECIFIED
}

func (x *InstallerInitRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type InstallerInitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *InstallerInitResponse) Reset() {
	*x = InstallerInitResponse{}
	mi := &file_rpc_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallerInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallerInitResponse) ProtoMessage() {}

func (x *InstallerInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallerInitResponse.ProtoReflect.Descriptor instead.
func (*InstallerInitResponse) Descriptor() ([]byte, []int) {
	return file_rpc_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *InstallerInitResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *InstallerInitResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type MetadataRepoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repourl  string `protobuf:"bytes,1,opt,name=repourl,proto3" json:"repourl,omitempty"`
	Metadata string `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *MetadataRepoRequest) Reset() {
	*x = MetadataRepoRequest{}
	mi := &file_rpc_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRepoRequest) ProtoMessage() {}

func (x *MetadataRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRepoRequest.ProtoReflect.Descriptor instead.
func (*MetadataRepoRequest) Descriptor() ([]byte, []int) {
	return file_rpc_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *MetadataRepoRequest) GetRepourl() string {
	if x != nil {
		return x.Repourl
	}
	return ""
}

func (x *MetadataRepoRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type MetadataRepoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *MetadataRepoResponse) Reset() {
	*x = MetadataRepoResponse{}
	mi := &file_rpc_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRepoResponse) ProtoMessage() {}

func (x *MetadataRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRepoResponse.ProtoReflect.Descriptor instead.
func (*MetadataRepoResponse) Descriptor() ([]byte, []int) {
	return file_rpc_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *MetadataRepoResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *MetadataRepoResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_rpc_metadata_proto protoreflect.FileDescriptor

var file_rpc_metadata_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaa, 0x01, 0x0a, 0x14, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65,
	0x72, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3e, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x15, 0x0a, 0x11, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x49, 0x4e, 0x49, 0x54, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x44, 0x4f, 0x4e, 0x45, 0x10, 0x02, 0x22, 0x6a, 0x0a, 0x15, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c,
	0x6c, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x22, 0x4b, 0x0a, 0x13, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x70, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x70,
	0x6f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6f,
	0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x69, 0x0a, 0x14, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0x9d, 0x01, 0x0a, 0x0f, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45,
	0x0a, 0x0c, 0x49, 0x6e, 0x69, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18,
	0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x6e, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0c, 0x52, 0x65, 0x70, 0x6f, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x65, 0x70, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x73, 0x65,
	0x63, 0x6b, 0x72, 0x69, 0x74, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_metadata_proto_rawDescOnce sync.Once
	file_rpc_metadata_proto_rawDescData = file_rpc_metadata_proto_rawDesc
)

func file_rpc_metadata_proto_rawDescGZIP() []byte {
	file_rpc_metadata_proto_rawDescOnce.Do(func() {
		file_rpc_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_metadata_proto_rawDescData)
	})
	return file_rpc_metadata_proto_rawDescData
}

var file_rpc_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_metadata_proto_goTypes = []any{
	(InstallerInitRequest_State)(0), // 0: pb.InstallerInitRequest.State
	(*InstallerInitRequest)(nil),    // 1: pb.InstallerInitRequest
	(*InstallerInitResponse)(nil),   // 2: pb.InstallerInitResponse
	(*MetadataRepoRequest)(nil),     // 3: pb.MetadataRepoRequest
	(*MetadataRepoResponse)(nil),    // 4: pb.MetadataRepoResponse
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_rpc_metadata_proto_depIdxs = []int32{
	0, // 0: pb.InstallerInitRequest.status:type_name -> pb.InstallerInitRequest.State
	5, // 1: pb.InstallerInitResponse.created_at:type_name -> google.protobuf.Timestamp
	5, // 2: pb.MetadataRepoResponse.created_at:type_name -> google.protobuf.Timestamp
	1, // 3: pb.MetadataService.InitMetadata:input_type -> pb.InstallerInitRequest
	3, // 4: pb.MetadataService.RepoMetadata:input_type -> pb.MetadataRepoRequest
	2, // 5: pb.MetadataService.InitMetadata:output_type -> pb.InstallerInitResponse
	4, // 6: pb.MetadataService.RepoMetadata:output_type -> pb.MetadataRepoResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpc_metadata_proto_init() }
func file_rpc_metadata_proto_init() {
	if File_rpc_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_metadata_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_metadata_proto_goTypes,
		DependencyIndexes: file_rpc_metadata_proto_depIdxs,
		EnumInfos:         file_rpc_metadata_proto_enumTypes,
		MessageInfos:      file_rpc_metadata_proto_msgTypes,
	}.Build()
	File_rpc_metadata_proto = out.File
	file_rpc_metadata_proto_rawDesc = nil
	file_rpc_metadata_proto_goTypes = nil
	file_rpc_metadata_proto_depIdxs = nil
}
