// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: rpc_alerts.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Lineno        int64                  `protobuf:"varint,3,opt,name=lineno,proto3" json:"lineno,omitempty"`
	Commitid      string                 `protobuf:"bytes,4,opt,name=commitid,proto3" json:"commitid,omitempty"`
	Secrettype    string                 `protobuf:"bytes,5,opt,name=secrettype,proto3" json:"secrettype,omitempty"`
	IsVerified    bool                   `protobuf:"varint,6,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretAlertRequest) Reset() {
	*x = SecretAlertRequest{}
	mi := &file_rpc_alerts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretAlertRequest) ProtoMessage() {}

func (x *SecretAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_alerts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretAlertRequest.ProtoReflect.Descriptor instead.
func (*SecretAlertRequest) Descriptor() ([]byte, []int) {
	return file_rpc_alerts_proto_rawDescGZIP(), []int{0}
}

func (x *SecretAlertRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SecretAlertRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *SecretAlertRequest) GetLineno() int64 {
	if x != nil {
		return x.Lineno
	}
	return 0
}

func (x *SecretAlertRequest) GetCommitid() string {
	if x != nil {
		return x.Commitid
	}
	return ""
}

func (x *SecretAlertRequest) GetSecrettype() string {
	if x != nil {
		return x.Secrettype
	}
	return ""
}

func (x *SecretAlertRequest) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

type SecretAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretAlertResponse) Reset() {
	*x = SecretAlertResponse{}
	mi := &file_rpc_alerts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretAlertResponse) ProtoMessage() {}

func (x *SecretAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_alerts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretAlertResponse.ProtoReflect.Descriptor instead.
func (*SecretAlertResponse) Descriptor() ([]byte, []int) {
	return file_rpc_alerts_proto_rawDescGZIP(), []int{1}
}

func (x *SecretAlertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_rpc_alerts_proto protoreflect.FileDescriptor

var file_rpc_alerts_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xb9, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x70,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x6c, 0x69, 0x6e, 0x65, 0x6e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6c,
	0x69, 0x6e, 0x65, 0x6e, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x69,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x6c, 0x65, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x32, 0x50, 0x0a, 0x0c, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x6c,
	0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x61, 0x78, 0x69, 0x6c, 0x6f, 0x63, 0x6b,
	0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rpc_alerts_proto_rawDescOnce sync.Once
	file_rpc_alerts_proto_rawDescData = file_rpc_alerts_proto_rawDesc
)

func file_rpc_alerts_proto_rawDescGZIP() []byte {
	file_rpc_alerts_proto_rawDescOnce.Do(func() {
		file_rpc_alerts_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_alerts_proto_rawDescData)
	})
	return file_rpc_alerts_proto_rawDescData
}

var file_rpc_alerts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_alerts_proto_goTypes = []any{
	(*SecretAlertRequest)(nil),  // 0: pb.SecretAlertRequest
	(*SecretAlertResponse)(nil), // 1: pb.SecretAlertResponse
}
var file_rpc_alerts_proto_depIdxs = []int32{
	0, // 0: pb.AlertService.SecretAlert:input_type -> pb.SecretAlertRequest
	1, // 1: pb.AlertService.SecretAlert:output_type -> pb.SecretAlertResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_alerts_proto_init() }
func file_rpc_alerts_proto_init() {
	if File_rpc_alerts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_alerts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_alerts_proto_goTypes,
		DependencyIndexes: file_rpc_alerts_proto_depIdxs,
		MessageInfos:      file_rpc_alerts_proto_msgTypes,
	}.Build()
	File_rpc_alerts_proto = out.File
	file_rpc_alerts_proto_rawDesc = nil
	file_rpc_alerts_proto_goTypes = nil
	file_rpc_alerts_proto_depIdxs = nil
}
