// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: rpc_commit.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommitDataService_SendCommitData_FullMethodName = "/pb.CommitDataService/SendCommitData"
)

// CommitDataServiceClient is the client API for CommitDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommitDataServiceClient interface {
	SendCommitData(ctx context.Context, in *SendCommitDataRequest, opts ...grpc.CallOption) (*SendCommitDataResponse, error)
}

type commitDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommitDataServiceClient(cc grpc.ClientConnInterface) CommitDataServiceClient {
	return &commitDataServiceClient{cc}
}

func (c *commitDataServiceClient) SendCommitData(ctx context.Context, in *SendCommitDataRequest, opts ...grpc.CallOption) (*SendCommitDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendCommitDataResponse)
	err := c.cc.Invoke(ctx, CommitDataService_SendCommitData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommitDataServiceServer is the server API for CommitDataService service.
// All implementations must embed UnimplementedCommitDataServiceServer
// for forward compatibility.
type CommitDataServiceServer interface {
	SendCommitData(context.Context, *SendCommitDataRequest) (*SendCommitDataResponse, error)
	mustEmbedUnimplementedCommitDataServiceServer()
}

// UnimplementedCommitDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommitDataServiceServer struct{}

func (UnimplementedCommitDataServiceServer) SendCommitData(context.Context, *SendCommitDataRequest) (*SendCommitDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommitData not implemented")
}
func (UnimplementedCommitDataServiceServer) mustEmbedUnimplementedCommitDataServiceServer() {}
func (UnimplementedCommitDataServiceServer) testEmbeddedByValue()                           {}

// UnsafeCommitDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommitDataServiceServer will
// result in compilation errors.
type UnsafeCommitDataServiceServer interface {
	mustEmbedUnimplementedCommitDataServiceServer()
}

func RegisterCommitDataServiceServer(s grpc.ServiceRegistrar, srv CommitDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedCommitDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommitDataService_ServiceDesc, srv)
}

func _CommitDataService_SendCommitData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCommitDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommitDataServiceServer).SendCommitData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommitDataService_SendCommitData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommitDataServiceServer).SendCommitData(ctx, req.(*SendCommitDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommitDataService_ServiceDesc is the grpc.ServiceDesc for CommitDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommitDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CommitDataService",
	HandlerType: (*CommitDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommitData",
			Handler:    _CommitDataService_SendCommitData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc_commit.proto",
}
