// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: runner/rpc_scan.proto

package runnerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunnerScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       string                 `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerScanRequest) Reset() {
	*x = RunnerScanRequest{}
	mi := &file_runner_rpc_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerScanRequest) ProtoMessage() {}

func (x *RunnerScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runner_rpc_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerScanRequest.ProtoReflect.Descriptor instead.
func (*RunnerScanRequest) Descriptor() ([]byte, []int) {
	return file_runner_rpc_scan_proto_rawDescGZIP(), []int{0}
}

func (x *RunnerScanRequest) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

type RunnerScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUrl       string                 `protobuf:"bytes,1,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerScanResponse) Reset() {
	*x = RunnerScanResponse{}
	mi := &file_runner_rpc_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerScanResponse) ProtoMessage() {}

func (x *RunnerScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runner_rpc_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerScanResponse.ProtoReflect.Descriptor instead.
func (*RunnerScanResponse) Descriptor() ([]byte, []int) {
	return file_runner_rpc_scan_proto_rawDescGZIP(), []int{1}
}

func (x *RunnerScanResponse) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

var File_runner_rpc_scan_proto protoreflect.FileDescriptor

const file_runner_rpc_scan_proto_rawDesc = "" +
	"\n" +
	"\x15runner/rpc_scan.proto\x12\x06runner\"-\n" +
	"\x11RunnerScanRequest\x12\x18\n" +
	"\arequest\x18\x01 \x01(\tR\arequest\"/\n" +
	"\x12RunnerScanResponse\x12\x19\n" +
	"\brepo_url\x18\x01 \x01(\tR\arepoUrl2U\n" +
	"\vScanService\x12F\n" +
	"\rStartRepoScan\x12\x19.runner.RunnerScanRequest\x1a\x1a.runner.RunnerScanResponseB\x19Z\x17axilock-runner/runnerpbb\x06proto3"

var (
	file_runner_rpc_scan_proto_rawDescOnce sync.Once
	file_runner_rpc_scan_proto_rawDescData []byte
)

func file_runner_rpc_scan_proto_rawDescGZIP() []byte {
	file_runner_rpc_scan_proto_rawDescOnce.Do(func() {
		file_runner_rpc_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runner_rpc_scan_proto_rawDesc), len(file_runner_rpc_scan_proto_rawDesc)))
	})
	return file_runner_rpc_scan_proto_rawDescData
}

var file_runner_rpc_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_runner_rpc_scan_proto_goTypes = []any{
	(*RunnerScanRequest)(nil),  // 0: runner.RunnerScanRequest
	(*RunnerScanResponse)(nil), // 1: runner.RunnerScanResponse
}
var file_runner_rpc_scan_proto_depIdxs = []int32{
	0, // 0: runner.ScanService.StartRepoScan:input_type -> runner.RunnerScanRequest
	1, // 1: runner.ScanService.StartRepoScan:output_type -> runner.RunnerScanResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runner_rpc_scan_proto_init() }
func file_runner_rpc_scan_proto_init() {
	if File_runner_rpc_scan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runner_rpc_scan_proto_rawDesc), len(file_runner_rpc_scan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runner_rpc_scan_proto_goTypes,
		DependencyIndexes: file_runner_rpc_scan_proto_depIdxs,
		MessageInfos:      file_runner_rpc_scan_proto_msgTypes,
	}.Build()
	File_runner_rpc_scan_proto = out.File
	file_runner_rpc_scan_proto_goTypes = nil
	file_runner_rpc_scan_proto_depIdxs = nil
}
